# Generated by Django 3.2.4 on 2021-06-04 15:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kraepelin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timeleft', models.IntegerField(blank=True, default=7200)),
                ('numeral_system', models.CharField(choices=[('latin', 'latin'), ('kanji', 'kanji')], default='latin', max_length=32)),
                ('numbers', models.CharField(blank=True, max_length=30000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('answers', models.CharField(max_length=30000)),
                ('results', models.CharField(max_length=30000, validators=[django.core.validators.RegexValidator(re.compile('^(-)?\\d+(?:,(-)?\\d+)*\\Z'), code='invalid', message=None)])),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('finished', 'finished')], default='active', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(default=server.models.generate_unique_key, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
